### PR TITLE
Add data SITREP

### PR DESCRIPTION
**Pull request by redshiftzero**
Here's an ipython notebook running some quick numbers on our data thus far: TL;DR we have 200k examples to 5.1k unique onion services. w00t

No reviewing requested here - this is a "check it out if you are interested PR"

Also one can steal this notebook and re-run this at a later date if you want to regenerate these numbers and plots to see how things are going 😉, you just need `$PGPASS` defined

### CODE REVIEW

**Comment by conorsch** [comment]
Evidently I could use a bit of a refresher on how to view this notebook locally. Is `jupyter notebook notebooks/data_crawling_status.ipynb` sufficient?

**Comment by redshiftzero** [comment]
Yep that will work. Conveniently Github will also render the notebook if you navigate to it: https://github.com/freedomofpress/fingerprint-securedrop/blob/add-data-state-notebook/notebooks/data_crawling_status.ipynb

**Comment by conorsch** [comment]
Excellent report, thank you for sharing this! It's a shame we had such low collection rates for a while, but glad to hear the bits are flowing now.

**Comment by psivesely** [comment]
Will review tomorrow!

**Comment by redshiftzero** [comment]
Feel free to peruse the notebook at your leisure 😃, but a review is not necessary here (see PR description), so I'm gonna go ahead and merge this one in. However I am about to submit another PR in this repo for you to review 😉

**Pull request merged**
