### PR TITLE
Refactor crawler

### PR DESCRIPTION
**Pull request by psivesely**
This refactor accomplishes the following:
- Replaces use of privoxy http -> socks5 proxy chaining with the aiosocks
  library.
- The sorter now self-manages all proxy and asyncio abstractions, as well as
  implements **exit** and **enter** methods, so it can be used with a `with`
  statement. This simplifies its use.
- Generalizes itself away from sorting just SecureDrops by implementing an
  simple interface for defining arbitrary classes and tests determining class
  membership through the config.ini.
- Retries services that weren't reached the first time.

To make the crawler more compatible with these arbitrary class designations,
some changes were made, though these are still somewhat limited in scope.

### CODE REVIEW

**Comment by psivesely** [comment]
Fixes #13.

**Comment by psivesely** [comment]
@redshiftzero Notice how the SD version is now the sub-folder name instead of in the control file... This is probably not the best because I should just stay consistent for now until #25 happens.

**Comment by redshiftzero** [comment]
Looks great! Nice re: the specification of the guard node too. Merging in.

**Comment by psivesely** [comment]
Lol, this was a sorter refactor. I messed up the title.

**Pull request merged**
